name: GNUmakefile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: install ncurses
      run: brew install ncurses
    - name: build all
      run: PKG_CONFIG_PATH="/usr/local/opt/ncurses/lib/pkgconfig" gmake
