name: GNUmakefile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: install ncurses
      run: |
        brew install ncurses
        echo 'export PATH="/usr/local/opt/ncurses/bin:$PATH"' \
          >>/Users/runner/.bash_profile
    - name: build all
      run: . ~/.bash_profile && make

  linux-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install ncurses
      run: apt install libncurses-dev clang lld libc++-dev
    - name: gcc build all
      run: CXX=g++ make
    - name: clang build all
      run: CXX=clang++ make
